# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51260014b5ffaebc869616148716b527"
name = "giftlist-reminder"
application_url = "https://confused-interesting-document-finals.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gen-fulo.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://confused-interesting-document-finals.trycloudflare.com/auth/callback",
  "https://confused-interesting-document-finals.trycloudflare.com/auth/shopify/callback",
  "https://confused-interesting-document-finals.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
